// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (code, original_url) 
VALUES ($1, $2)
RETURNING code, original_url, created_at
`

type CreateURLParams struct {
	Code        string
	OriginalUrl string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Code, arg.OriginalUrl)
	var i Url
	err := row.Scan(&i.Code, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}

const getURL = `-- name: GetURL :one
SELECT original_url FROM urls 
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetURL(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, getURL, code)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}
