name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Run Go tests
        run: go test -v ./...

  deploy:
    name: Deploy to server
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/url-short
            git pull origin main
            docker compose up --build -d
